Allow BaseExperiment to accept experiment configuration directly
FFede0/RL4CC pull request #13
Opened 2024-06-04 14:34 UTC by ema-pe

This PR implements the feature discussed in #10.

To test this feature, you can download the attached sample project that calls TrainingExperiment with different combinations of exp_config, exp_config_file (and env_config and ray_config). You need to have RL4CC installed (and the `test-ep-10` branch) in the RL4CC directory of the example project. To run the tests, do `python main.py`.

Project: [test-ep-10.zip](https://github.com/user-attachments/files/15561196/test-ep-10.zip)

Closes #10.

~~Edit: I forgot to document the feature. I'll add a new commit in the next few hours.~~ Done.

2024-06-04 14:53 UTC, ema-pe commented
**Question**: should I allow `tune_config` to be given directly instead of using `tune_config_file`?

https://github.com/FFede0/RL4CC/blob/a14bd81ac2c12aacbe5df26c4df8fea76d0ea6d3/experiments/tune.py#L36-L44

https://github.com/FFede0/RL4CC/blob/test/config_files/README.md#tuner-configuration-file

2024-06-04 14:59 UTC, FFede0 commented
> **Question**: should I allow `tune_config` to be given directly instead of using `tune_config_file`?
> 
> https://github.com/FFede0/RL4CC/blob/a14bd81ac2c12aacbe5df26c4df8fea76d0ea6d3/experiments/tune.py#L36-L44
> 
> https://github.com/FFede0/RL4CC/blob/test/config_files/README.md#tuner-configuration-file

To be coherent, I’d say yes

2024-06-04 15:25 UTC, ema-pe commented
> > **Question**: should I allow `tune_config` to be given directly instead of using `tune_config_file`?
> > https://github.com/FFede0/RL4CC/blob/a14bd81ac2c12aacbe5df26c4df8fea76d0ea6d3/experiments/tune.py#L36-L44
> > 
> > https://github.com/FFede0/RL4CC/blob/test/config_files/README.md#tuner-configuration-file
> 
> To be coherent, I’d say yes

Done. I also updated the documentation to be coherent. I tested the code for TrainingExperiment, but not for TuningExperiment.

You can see the updated documentation here: https://github.com/FFede0/RL4CC/tree/test

2024-06-07 13:59 UTC, FFede0 requested changes
Address comments to single files

2024-06-07 13:59 UTC, FFede0 commented on README.md
> +  `envconfig` and `ray_config`) used to define the experiment, saved as JSON
Typo: `env_config`

2024-06-07 13:59 UTC, FFede0 commented on README.md
> +>   - The configuration is saved as files even if you pass to RL4CC dictionaries
JSON files are saved here, regardless the fact that the user passed the configuration(s) as file(s) or as `dict` object(s)

2024-06-07 13:59 UTC, FFede0 commented on config_files/README.md
>  :warning::warning::warning: **Important note:** there are few elements that,
I'm bothered by the coexistence of different formats. Please, write these as your "warnings"

2024-06-07 13:59 UTC, FFede0 commented on experiments/base_experiment.py
> +      if defined("env_config_file", self.exp_config):
It makes sense to have defined...but I'd remove not_defined, then, or implement it as `return not defined(...)`

2024-06-07 13:59 UTC, FFede0 commented on utilities/common.py
> +def defined(param: str, params_dict: dict) -> bool:
See comment to base_experiment.py

2024-07-17 12:54 UTC, FFede0 approved these changes

2024-07-17 12:54 UTC, merged