Callbacks for plots
FFede0/RL4CC pull request #15
Opened 2024-07-20 11:30 UTC by wakephul

Integrated classes for automatic plot creation / custom metrics management

2024-07-20 12:14 UTC, FFede0 requested changes
Please, fix the comments attached to each file

2024-07-20 12:14 UTC, FFede0 commented on README.md
README.md should be kept as in the current `test` version, since it now includes references to the fact that the configuration can be provided both as files and as dictionaries.

Additionally, please add few comments on how to use the plot functionalities

2024-07-20 12:14 UTC, FFede0 commented on algorithms/generators/algo_config_generator.py
Please, restore the version in `test`: lines 363--367 are a duplicate of the above, & line 406 will plot useless horizontal lines if the `1` is dropped

2024-07-20 12:14 UTC, FFede0 commented on config_files/README.md
README.md should be kept as in the current test version, since it now includes references to the fact that the configuration can be provided both as files and as dictionaries.

2024-07-20 12:14 UTC, FFede0 commented on experiments/tune.py
Please, restore the `test` version (wrong indentation here!)

2024-07-20 12:14 UTC, FFede0 commented on experiments/train_with_plots.py
Line 19 has an absolute path to your own home

2024-07-21 07:26 UTC, wakephul commented
@FFede0 thanks for the review, should be fixed now

2024-07-21 08:40 UTC, FFede0 requested changes
Please, check the comment in file

2024-07-21 08:40 UTC, FFede0 commented on experiments/tune.py
Line 42: shouldn't `Logger` have lowercase `l`? `warn` should not be a static method of the `Logger` class

2024-07-21 16:01 UTC, FFede0 approved these changes

2024-07-21 16:01 UTC, merged