Evaluations in json format
FFede0/RL4CC pull request #16
Opened 2024-07-22 14:37 UTC by wakephul

Saving evaluations in json format instead of txt
Secondary fixes

2024-07-22 16:04 UTC, FFede0 requested changes
Please, address comments attached to files

2024-07-22 16:04 UTC, FFede0 commented on experiments/tune.py
This is an error: the tune config can still be provided (and it is not ignored) when a previous checkpoint is given: it can be used to provide information about whether to restart previously errored tests, whether to restart or resume running tests, etc.
I will update the documentation to make it more clear, but please do not override the last change

2024-07-22 16:04 UTC, FFede0 commented on experiments/base_experiment.py
Please, update also the README file: somewhere we wrote that evaluations are saved in a txt file

2024-07-23 08:05 UTC, FFede0 requested changes
Sorry, I've just noticed a couple of things in the TrainingExperimentWithPlots

2024-07-23 08:05 UTC, FFede0 commented on experiments/train_with_plots.py
Please:
- restore the `__init__` implementation: some parameters are missing from yours
- drop the `run` method, since it is just calling the parent version
- restore the indentation and use of `"` from the version in the `test` branch, it looks like you've edited the whole file instead of just fixing the lines related to evaluations

2024-07-23 08:45 UTC, wakephul commented on experiments/train_with_plots.py
don't really know what's going on here. there must be something wrong in git history at this point, since I haven't changed anything in this file

anyways, I restored the previous version (from `test`)

2024-07-23 14:57 UTC, FFede0 approved these changes

2024-07-23 14:57 UTC, merged